In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!pip install openpyxl

In [3]:
book = pd.read_excel('books.xlsx')

In [4]:
books=book

In [5]:
books.head()

bookID                                              title  \
0     1.0  Harry Potter and the Half-Blood Prince (Harry ...   
1     2.0  Harry Potter and the Order of the Phoenix (Har...   
2     4.0  Harry Potter and the Chamber of Secrets (Harry...   
3     5.0  Harry Potter and the Prisoner of Azkaban (Harr...   
4     8.0  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   

                       authors average_rating        isbn         isbn13  \
0  J.K. Rowling/Mary GrandPr̩           4.57   439785960  9780000000000   
1  J.K. Rowling/Mary GrandPr̩           4.49   439358078  9780000000000   
2                 J.K. Rowling           4.42   439554896  9780000000000   
3  J.K. Rowling/Mary GrandPr̩           4.56  043965548X  9780000000000   
4  J.K. Rowling/Mary GrandPr̩           4.78   439682584  9780000000000   

  language_code num_pages  ratings_count  text_reviews_count  \
0           eng       652      2095690.0             27591.0   
1           eng       870      2153167.0             29221.0   
2           eng       352         6333.0               244.0   
3           eng       435      2339585.0             36325.0   
4           eng      2690        41428.0               164.0   

      publication_date        publisher Unnamed: 12  
0  2006-09-16 00:00:00  Scholastic Inc.         NaN  
1  2004-09-01 00:00:00  Scholastic Inc.         NaN  
2  2003-11-01 00:00:00       Scholastic         NaN  
3  2004-05-01 00:00:00  Scholastic Inc.         NaN  
4  2004-09-13 00:00:00       Scholastic         NaN

In [6]:
books.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher', 'Unnamed: 12'],
      dtype='object')

In [7]:
books.drop([ 'isbn13','Unnamed: 12','language_code','num_pages','ratings_count','text_reviews_count','publication_date'],axis=1,inplace=True)

In [8]:
books.rename(columns={'authors':'author','Year-Of-Publication':'year','Publisher':'publisher','publication_date':'year','isbn':'ISBN'},inplace=True)

In [9]:
books.head()

bookID                                              title  \
0     1.0  Harry Potter and the Half-Blood Prince (Harry ...   
1     2.0  Harry Potter and the Order of the Phoenix (Har...   
2     4.0  Harry Potter and the Chamber of Secrets (Harry...   
3     5.0  Harry Potter and the Prisoner of Azkaban (Harr...   
4     8.0  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   

                        author average_rating        ISBN        publisher  
0  J.K. Rowling/Mary GrandPr̩           4.57   439785960  Scholastic Inc.  
1  J.K. Rowling/Mary GrandPr̩           4.49   439358078  Scholastic Inc.  
2                 J.K. Rowling           4.42   439554896       Scholastic  
3  J.K. Rowling/Mary GrandPr̩           4.56  043965548X  Scholastic Inc.  
4  J.K. Rowling/Mary GrandPr̩           4.78   439682584       Scholastic

In [10]:
books.rename(columns={'Book-Title':'title','Book-Author':'author','Year-Of-Publication':'year','Publisher':'publisher'},inplace=True)

In [11]:
books.head()

bookID                                              title  \
0     1.0  Harry Potter and the Half-Blood Prince (Harry ...   
1     2.0  Harry Potter and the Order of the Phoenix (Har...   
2     4.0  Harry Potter and the Chamber of Secrets (Harry...   
3     5.0  Harry Potter and the Prisoner of Azkaban (Harr...   
4     8.0  Harry Potter Boxed Set  Books 1-5 (Harry Potte...   

                        author average_rating        ISBN        publisher  
0  J.K. Rowling/Mary GrandPr̩           4.57   439785960  Scholastic Inc.  
1  J.K. Rowling/Mary GrandPr̩           4.49   439358078  Scholastic Inc.  
2                 J.K. Rowling           4.42   439554896       Scholastic  
3  J.K. Rowling/Mary GrandPr̩           4.56  043965548X  Scholastic Inc.  
4  J.K. Rowling/Mary GrandPr̩           4.78   439682584       Scholastic

In [12]:
books.isnull().sum()

bookID            5
title             5
author            5
average_rating    5
ISBN              5
publisher         5
dtype: int64

In [13]:
books.dropna(inplace=True)

In [14]:
books['average_rating'] = pd.to_numeric(books['average_rating'], errors='coerce')

book_pivot = books.pivot_table(columns='bookID', index='title', values='average_rating')

In [15]:
book_pivot.fillna(0,inplace=True)
book_pivot.head()

bookID                                              1.0      2.0      4.0      \
title                                                                           
2023-11-09 00:00:00                                     0.0      0.0      0.0   
  said the shotgun to the head.                         0.0      0.0      0.0   
$30 Film School: How to Write  Direct  Produce ...      0.0      0.0      0.0   
1 000 Places to See Before You Die                      0.0      0.0      0.0   
10 lb Penalty                                           0.0      0.0      0.0   

bookID                                              5.0      8.0      9.0      \
title                                                                           
2023-11-09 00:00:00                                     0.0      0.0      0.0   
  said the shotgun to the head.                         0.0      0.0      0.0   
$30 Film School: How to Write  Direct  Produce ...      0.0      0.0      0.0   
1 000 Places to See Before You Die                      0.0      0.0      0.0   
10 lb Penalty                                           0.0      0.0      0.0   

bookID                                              10.0     12.0     13.0     \
title                                                                           
2023-11-09 00:00:00                                     0.0      0.0      0.0   
  said the shotgun to the head.                         0.0      0.0      0.0   
$30 Film School: How to Write  Direct  Produce ...      0.0      0.0      0.0   
1 000 Places to See Before You Die                      0.0      0.0      0.0   
10 lb Penalty                                           0.0      0.0      0.0   

bookID                                              14.0     ...  45617.0  \
title                                                        ...            
2023-11-09 00:00:00                                     0.0  ...      0.0   
  said the shotgun to the head.                         0.0  ...      0.0   
$30 Film School: How to Write  Direct  Produce ...      0.0  ...      0.0   
1 000 Places to See Before You Die                      0.0  ...      0.0   
10 lb Penalty                                           0.0  ...      0.0   

bookID                                              45623.0  45625.0  45626.0  \
title                                                                           
2023-11-09 00:00:00                                     0.0      0.0      0.0   
  said the shotgun to the head.                         0.0      0.0      0.0   
$30 Film School: How to Write  Direct  Produce ...      0.0      0.0      0.0   
1 000 Places to See Before You Die                      0.0      0.0      0.0   
10 lb Penalty                                           0.0      0.0      0.0   

bookID                                              45630.0  45631.0  45633.0  \
title                                                                           
2023-11-09 00:00:00                                     0.0      0.0      0.0   
  said the shotgun to the head.                         0.0      0.0      0.0   
$30 Film School: How to Write  Direct  Produce ...      0.0      0.0      0.0   
1 000 Places to See Before You Die                      0.0      0.0      0.0   
10 lb Penalty                                           0.0      0.0      0.0   

bookID                                              45634.0  45639.0  45641.0  
title                                                                          
2023-11-09 00:00:00                                     0.0      0.0      0.0  
  said the shotgun to the head.                         0.0      0.0      0.0  
$30 Film School: How to Write  Direct  Produce ...      0.0      0.0      0.0  
1 000 Places to See Before You Die                      0.0      0.0      0.0  
10 lb Penalty                                           0.0      0.0      0.0  

[5 rows x 11119 columns]

In [16]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute')

In [17]:
from scipy.sparse import csr_matrix
book_sparse=csr_matrix(book_pivot)

In [18]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [19]:
book_pivot.iloc[240].shape

(11119,)

In [20]:
distances,suggestions=model.kneighbors(book_pivot.iloc[240].values.reshape(1,-1),n_neighbors=6)

In [21]:
suggestions

array([[ 240,  555,  876, 1183,  653,  537]], dtype=int64)

In [22]:
distances

array([[0.  , 4.18, 4.18, 4.18, 4.18, 4.18]])

In [23]:
book_pivot.iloc[240].values

array([0., 0., 0., ..., 0., 0., 0.])

In [24]:
for i in range(len(suggestions)):
    print(book_pivot.index[suggestions[i]])

Index(['A Perfect Vacuum', 'American Writers  Supplement VIII',
       'Beckett Football Card Price Guide',
       'Brodie's notes on Aldous Huxley's brave new world',
       'Anthony Thwaite: In Conversation With Peter Dale and Ian Hamilton',
       'American Film Guide'],
      dtype='object', name='title')


In [25]:
def recommend_book(book_name):
    book_id=np.where(book_pivot.index==book_name)[0][0]
    distances,suggestions=model.kneighbors(book_pivot.iloc[book_id].values.reshape(1,-1),n_neighbors=6)
    
    for i in range(len(suggestions)):
            print(book_pivot.index[suggestions[i]])

In [26]:
recommend_book('Exclusive')

Index(['Exclusive', 'American Film Guide',
       'Brodie's notes on Aldous Huxley's brave new world',
       'Beckett Football Card Price Guide',
       'Anthony Thwaite: In Conversation With Peter Dale and Ian Hamilton',
       'American Writers  Supplement VIII'],
      dtype='object', name='title')
